title: Qiang Wang's Homepage
page-top-title: Qiang Wang 
top-section-bg-text: Intelligent Transportation
home-subtitle: Qiang Wang&ensp;|&ensp;王强
copyright-text: '&copy; Qiang Wang 2023-2026. All Rights Reserved.'
